server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shy?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qf.pojo
<<<<<<< HEAD
=======
#mail:
#  default-encoding: utf-8
#  host: smtp.qq.com
#  username: 714338547@qq.com
#  password: gbubjivndekzbffj
#properties:
#    mail:
#      smtp:
#        auth: true
#        starttls:
#          enable: true
#          required: true
mail:
  default-encoding: utf-8
  host: smtp.qq.com
  username: 714338547@qq.com
  password: gbubjivndekzbffj
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true



>>>>>>> origin/master
